In [1]:
import numpy as np

In [2]:
vector = np.zeros(10)

In [4]:
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
vector_memory_size = vector.size * vector.itemsize

In [7]:
print(vector_memory_size)

80


In [8]:
print(np.info(np. add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [9]:
vector2 = np.arange(10, 50)

In [10]:
reversed_vector2 = vector2[::-1]

In [11]:
print(reversed_vector2)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [12]:
matrix = np.arange(0, 9).reshape(3,3)

In [13]:
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
non_zero_array = np.nonzero([1,2,0,0,4,0])

In [15]:
print(non_zero_array)

(array([0, 1, 4]),)


In [20]:
diagonal_matrix = np.eye(3)

In [21]:
print(diagonal_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
duplicate_matrix = np.tile(np.arange(5), (5,1))

In [30]:
print(duplicate_matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [35]:
zero_to_one_array = np.linspace(0.1,0.9,10)

In [36]:
print(zero_to_one_array)

[0.1        0.18888889 0.27777778 0.36666667 0.45555556 0.54444444
 0.63333333 0.72222222 0.81111111 0.9       ]


In [48]:
vector_for_sorting = np.random.randint(1,10,size=10)

In [49]:
vector_for_sorting

array([9, 3, 5, 3, 8, 9, 6, 7, 8, 7])

In [50]:
sorted_vector = np.sort(vector_for_sorting)

In [51]:
print(sorted_vector)

[3 3 5 6 7 7 8 8 9 9]


In [58]:
print(np.iinfo('int8'))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------



In [66]:
int_info = ['int8', 'int32', 'int64']

In [67]:
float_info = ['float32', 'float64']

In [82]:
for int in int_info:
    print(f"{int}:\nMin value {np.iinfo(int).min}\nMax value {np.iinfo(int).max}\n")
for float in float_info:
    print(f"{float}:\nMin value {np.finfo(float).min}\nMax value {np.finfo(float).max}\n")

int8:
Min value -128
Max value 127

int32:
Min value -2147483648
Max value 2147483647

int64:
Min value -9223372036854775808
Max value 9223372036854775807

float32:
Min value -3.4028234663852886e+38
Max value 3.4028234663852886e+38

float64:
Min value -1.7976931348623157e+308
Max value 1.7976931348623157e+308



In [83]:
float_array = np.array([1.5, 2.8, -3.2, 4.7, -5.9])

In [84]:
float_array_to_int = float_array.astype(np.int32)

In [85]:
print(float_array_to_int)

[ 1  2 -3  4 -5]


In [86]:
matrix_mean = matrix.mean(1)

In [87]:
print(matrix_mean)

[1. 4. 7.]


In [88]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
new_array = np.array([[122, 3, 4],
                     [1, 3123, 3],
                     [42, 6, 15]])

In [96]:
first_column_sorted_array = new_array[np.argsort(new_array[:, 0])]

In [101]:
print(first_column_sorted_array)

[[   1 3123    3]
 [  42    6   15]
 [ 122    3    4]]


In [102]:
swapped_array = first_column_sorted_array

In [103]:
swapped_array[[0,1]] = first_column_sorted_array[[1,0]]

In [104]:
print(swapped_array)

[[  42    6   15]
 [   1 3123    3]
 [ 122    3    4]]


In [134]:
random_array = np.array([1,5,6,4,5,1,2,3])

In [135]:
C = np.bincount(random_array)

In [140]:
A = np.repeat(np.arange(len(C)), C)

In [141]:
print(C)

[0 2 1 1 1 2 1]


In [142]:
print(np.bincount(A))

[0 2 1 1 1 2 1]
