In [5]:
import numpy as np

# Matrix Manipulation

In [6]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)

In [7]:
data

array([[77, 27, 81, 34, 27],
       [ 6, 57, 48, 29, 82],
       [99, 76, 95, 53,  1],
       [11, 27, 71,  1, 32],
       [19, 54, 80, 49, 51]])

In [8]:
data[[1,3]] = data[[3,1]]

In [9]:
print(data)

[[77 27 81 34 27]
 [11 27 71  1 32]
 [99 76 95 53  1]
 [ 6 57 48 29 82]
 [19 54 80 49 51]]


# Normalization

In [10]:
min_value = np.min(data)

In [11]:
max_value = np.max(data)

In [12]:
print((data - min_value) / (max_value - min_value))

[[0.7755102  0.26530612 0.81632653 0.33673469 0.26530612]
 [0.10204082 0.26530612 0.71428571 0.         0.31632653]
 [1.         0.76530612 0.95918367 0.53061224 0.        ]
 [0.05102041 0.57142857 0.47959184 0.28571429 0.82653061]
 [0.18367347 0.54081633 0.80612245 0.48979592 0.51020408]]


# Z-score normalization

In [13]:
mean = np.mean(data, axis=0)

In [14]:
std = np.std(data, axis=0)

In [15]:
print((data - mean) / std)

[[ 0.90806455 -1.12271507  0.3863337   0.04342698 -0.43056383]
 [-0.8240817  -1.12271507 -0.2575558  -1.74793608 -0.24497597]
 [ 1.48544663  1.47223957  1.28777902  1.07481784 -1.39562068]
 [-0.9553049   0.46603267 -1.73850167 -0.22799166  1.61090259]
 [-0.61412458  0.3071579   0.32194475  0.85768292  0.46025788]]


# Array splitting

In [16]:
splitted_data = np.array_split(np.ravel(data), 5)

In [17]:
for array in splitted_data:
    print(array)

[77 27 81 34 27]
[11 27 71  1 32]
[99 76 95 53  1]
[ 6 57 48 29 82]
[19 54 80 49 51]


# Dot product

In [18]:
vector1 = np.array([3, 5, 6, 7, 8])

In [19]:
vector2 = np.array([2, 4, 6, 8, 10])

In [20]:
dot_product = np.dot(vector1, vector2)

In [21]:
print(dot_product)

198


# Matrix multiplication

In [22]:
data2 = np.array(np.random.randint(1, 100, size=9)).reshape(3,3)

In [23]:
data_part_3_3 = data[:3, :3]

In [24]:
data2

array([[93, 20,  6],
       [20, 74, 98],
       [18, 50, 87]])

In [25]:
dot_product_matrix = np.dot(data_part_3_3, data2)

In [26]:
print(dot_product_matrix)

[[ 9159  7588 10155]
 [ 2841  5768  8889]
 [12437 12354 16307]]


# Identity matrix

In [27]:
identity_matrix = np.identity(3) * 2

In [28]:
inverse_matrix = np.linalg.inv(identity_matrix)

In [29]:
print(inverse_matrix)

[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


# Eigenvalues and eigenvectors

In [171]:
eigenvalues, eigenvectors = np.linalg.eig(data_part_3_3)

In [172]:
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [202.65330479  30.04782596 -33.70113075]
Eigenvectors:
 [[-0.56003856 -0.65715848 -0.30177476]
 [-0.34037422  0.74180763 -0.70104936]
 [-0.75531596  0.13365695  0.64611283]]


# Find missing values

## Replacing values

In [207]:
new_data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)

In [208]:
new_data = new_data.astype('float16')

In [209]:
new_data

array([[11., 88., 95., 76., 96.],
       [54., 56., 42., 97., 27.],
       [59., 64., 96.,  2., 45.],
       [91., 18., 74.,  2., 15.],
       [40., 42., 60., 95., 97.]], dtype=float16)

In [221]:
random_idx = np.random.choice(range(25), size=5, replace=False)

In [222]:
random_idx

array([20, 22, 18,  4,  0])

In [223]:
num_rows, num_cols = new_data.shape

In [224]:
num_rows

5

In [225]:
row_indices = random_idx // num_cols

In [226]:
column_indices = random_idx % num_cols

In [227]:
new_data[row_indices, column_indices] = np.nan

In [228]:
print(new_data)

[[nan 88. 95. 76. nan]
 [54. 56. 42. 97. 27.]
 [59. 64. 96.  2. 45.]
 [91. 18. 74. nan 15.]
 [nan 42. nan 95. 97.]]


## Finding missing values

In [229]:
row_indices2, column_indices2 = np.where(np.isnan(new_data))

In [230]:
print(row_indices2,column_indices2)

[0 0 3 4 4] [0 4 3 0 2]


# Replace missing values

In [231]:
data_with_replaced_nan = new_data.copy()

In [235]:
matrix_mean = np.nanmean(data_with_replaced_nan)

In [236]:
data_with_mean = np.where(np.isnan(data_with_replaced_nan), matrix_mean, data_with_replaced_nan)

In [237]:
print(data_with_mean)

[[61.66 88.   95.   76.   61.66]
 [54.   56.   42.   97.   27.  ]
 [59.   64.   96.    2.   45.  ]
 [91.   18.   74.   61.66 15.  ]
 [61.66 42.   61.66 95.   97.  ]]
