In [1]:
import numpy as np

### Arange

In [2]:
array = np.arange(1, 100)

In [3]:
array_decimal = np.arange(0, 10, 0.1)

In [4]:
array_decimal

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [5]:
array_decimal.shape

(100,)

In [6]:
array_decimal.reshape(10, 10)

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9],
       [6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9],
       [7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9],
       [8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9],
       [9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

### Linspace

In [9]:
lin_array = np.linspace(0, 5, 100) # create specific number of items at a specific range 

In [10]:
lin_array

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

### Random

In [13]:
np.random.randint(0, 10) # random integer between 0 and 10 (excluded)

1

In [15]:
np.random.rand(2, 2) # create an array with a specific shape with random floats

array([[0.01923185, 0.34764337],
       [0.28453006, 0.72729846]])

## Exercises

In [16]:
# 1. Using np.arange(): Use np.arange() to generate a sequence of numbers from 20 to 30 (inclusive).
# Print the resulting array. Expected output: [20 21 22 23 24 25 26 27 28 29 30]
np.arange(10,31)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [17]:
# 2. Using np.arange() with a step size: 
# Use np.arange() to generate a sequence of even numbers from 10 to 20 (inclusive). Print the resulting array.
# Expected output: [10 12 14 16 18 20]
np.arange(10, 21, 2)

array([10, 12, 14, 16, 18, 20])

In [18]:
# 3. Using np.linspace(): Use np.linspace() to generate a sequence of 5 numbers,
# evenly spaced between 0 and 1 (inclusive). Print the resulting array. Expected output: [0. 0.25 0.5 0.75 1. ]
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
# 4. Using np.random.rand(): Use np.random.rand() to generate an array of 3 random numbers between 0 and 1.
# Print the resulting array. Expected output: [0.123 0.456 0.789]. Note: Output will vary as it's random
np.random.rand(3)

array([0.44327366, 0.60543811, 0.95434522])

In [21]:
# 5. Using np.random.randint(): Use np.random.randint() to generate an array of 4 random integers between 1 and 10. 
# Print the resulting array. Expected output: [2 5 1 8].
# Note: Output will vary as it's random
np.random.randint(1, 10, 4)

array([6, 5, 6, 4])