In [1]:
import numpy as np

## One dimsional indexing

In [2]:
one_dim_array = np.arange(11)

In [3]:
one_dim_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
one_dim_array[0] # first

0

In [5]:
one_dim_array[-1] # last

10

In [6]:
one_dim_array[1:5]

array([1, 2, 3, 4])

In [7]:
one_dim_array[2::2] # [start:end:step]
# array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 2,  4,  6,  8, 10])

## Two dimsional indexing

In [8]:
two_dim_array = np.arange(10)

In [9]:
two_dim_array # 2, 5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
two_dim_array.size

10

In [11]:
two_dim_array.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
two_dim_array = two_dim_array.reshape((5,2))

In [14]:
two_dim_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
two_dim_array[1:3] # indexing through rows

array([[2, 3],
       [4, 5]])

In [17]:
two_dim_array[1:3, 0] # indexing through rows + taking the 1st item

array([2, 4])

In [19]:
two_dim_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
two_dim_array[::-1] # reversing the array

array([[8, 9],
       [6, 7],
       [4, 5],
       [2, 3],
       [0, 1]])

## Exercises

In [21]:
# 1. Indexing a 1D array: Create a 1D NumPy array with the numbers from 10 to 20 (inclusive). 
# Access and print the element at index 3. 
array1 = np.arange(10, 21)
array1[3]

13

In [22]:
# 2. Indexing a 2D array: Create a 2D NumPy array with the following values: 
# array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).
# Access and print the element at row 1 and column 2. 
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d[1, 2]

6

In [23]:
# 3. Slicing a 1D array: Create a 1D NumPy array with the numbers from 0 to 9 (inclusive).
# Slice the array to extract the elements from index 2 to index 6 (excluding index 6).
# Print the resulting slice. 
array2 = np.arange(0, 10)
array2[2:6]

array([2, 3, 4, 5])

In [25]:
# 4. Slicing a 2D array: Create a 2D NumPy array with the following values:
# array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).
# Slice the array to extract the subarray consisting of the first two rows and the last two columns.
# Print the resulting subarray.
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d[:2, 1:]

array([[2, 3],
       [5, 6]])