In [1]:
import numpy as np

In [3]:
two_dim_array = np.arange(0, 25)

In [4]:
two_dim_array = two_dim_array.reshape((5,5))

In [8]:
two_dim_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# X - 0 (columns)
# Y - 1 (rows)

### The mean

In [6]:
numbers = np.array([1,2,3,4,5]) 

In [7]:
numbers.mean() # (1+2+3+4+5) / 5 = 3.0

3.0

In [9]:
two_dim_array.mean()

12.0

In [11]:
two_dim_array.mean(axis=0)

array([10., 11., 12., 13., 14.])

In [10]:
two_dim_array.mean(axis=1)

array([ 2.,  7., 12., 17., 22.])

### Sorting

In [12]:
two_dim_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
sorted_indices = two_dim_array.argsort() # produce the sorting order based on the rows

In [22]:
np.take_along_axis(two_dim_array, sorted_indices, axis=1) 

array([[ 0,  6, 12, 18, 24],
       [ 0,  6, 12, 18, 24],
       [ 0,  6, 12, 18, 24],
       [ 0,  6, 12, 18, 24],
       [ 0,  6, 12, 18, 24]])

In [16]:
two_dim_array.argsort(axis=0) # produce the sorting order based on the columns

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [17]:
two_dim_array[two_dim_array[:,1].argsort()]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
two_dim_array[two_dim_array[:,1].argsort(axis=0)]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Swapping

In [23]:
two_dim_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
two_dim_array[[0, 1]] = two_dim_array[[1, 0]]

In [25]:
two_dim_array

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])