## Intro

In [3]:
import numpy as np # Numerical Python

In [4]:
array = np.array([1,2,3,4,5]) # numpy array 

In [5]:
array

array([1, 2, 3, 4, 5])

In [6]:
array2 = np.array([1,2,3,4,5])

In [7]:
array * array2

array([ 1,  4,  9, 16, 25])

## Numpy array attributes

In [11]:
array.ndim # number of dimensions

1

In [9]:
two_dim_array = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])

In [10]:
two_dim_array

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [12]:
two_dim_array.ndim

2

In [13]:
# shape - amount of rows/colums etc. 
array.shape

(5,)

In [14]:
two_dim_array.shape

(3, 5)

In [15]:
# size
two_dim_array.size

15

In [16]:
# data type
two_dim_array.dtype

dtype('int64')

### converting array to different type

In [17]:
float_array = array.astype('float16')

In [18]:
float_array.dtype

dtype('float16')

In [19]:
float_array

array([1., 2., 3., 4., 5.], dtype=float16)

## creating arrays

In [20]:
my_array = np.arange(1, 10)

In [21]:
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Exercises

In [25]:
# 1. Creating NumPy arrays : Create a 1D NumPy array with the numbers from 10 to 20 (inclusive), and print it.
one_dim_array = np.arange(10, 21)

In [26]:
one_dim_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
# 2. Array properties: For the array you created, print its number of dimensions (ndim), shape (shape), number of elements (size), and data type (dtype).

In [29]:
one_dim_array.ndim

1

In [30]:
one_dim_array.shape

(11,)

In [31]:
one_dim_array.size

11

In [32]:
one_dim_array.dtype

dtype('int64')

In [33]:
# 3
one_dim_array_float = np.arange(10, 21, dtype='float16')

In [34]:
one_dim_array_float

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
      dtype=float16)

In [35]:
# 4
one_dim_array * 2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])