In [2]:
import numpy as np

# Matrix Manipulation

In [3]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)

In [4]:
data

array([[14, 48, 90, 42, 11],
       [76,  2, 74, 10, 42],
       [44, 22, 46, 75, 45],
       [57, 55, 45, 90, 28],
       [26, 71, 18, 42, 31]])

In [5]:
data[[1,3]] = data[[3,1]]

In [6]:
print(data)

[[14 48 90 42 11]
 [57 55 45 90 28]
 [44 22 46 75 45]
 [76  2 74 10 42]
 [26 71 18 42 31]]


# Normalization

In [7]:
min_value = np.min(data)

In [8]:
max_value = np.max(data)

In [9]:
print((data - min_value) / (max_value - min_value))

[[0.13636364 0.52272727 1.         0.45454545 0.10227273]
 [0.625      0.60227273 0.48863636 1.         0.29545455]
 [0.47727273 0.22727273 0.5        0.82954545 0.48863636]
 [0.84090909 0.         0.81818182 0.09090909 0.45454545]
 [0.27272727 0.78409091 0.18181818 0.45454545 0.32954545]]


# Z-score normalization

In [10]:
mean = np.mean(data, axis=0)

In [11]:
std = np.std(data, axis=0)

In [12]:
print((data - mean) / std)

[[-1.33769093  0.34194971  1.41369473 -0.3492524  -1.69389416]
 [ 0.6187958   0.6269078  -0.38337484  1.36137161 -0.28231569]
 [ 0.02729981 -0.71646606 -0.34343996  0.82680161  1.12926278]
 [ 1.48328994 -1.53063203  0.77473666 -1.48966841  0.88016069]
 [-0.79169463  1.27824058 -1.46161659 -0.3492524  -0.03321361]]


# Array splitting

In [16]:
splitted_data = np.array_split(np.ravel(data), 5)

In [21]:
for array in splitted_data:
    print(array)

[14 48 90 42 11]
[57 55 45 90 28]
[44 22 46 75 45]
[76  2 74 10 42]
[26 71 18 42 31]


# Dot product

In [24]:
vector1 = np.array([3, 5, 6, 7, 8])

In [25]:
vector2 = np.array([2, 4, 6, 8, 10])

In [26]:
dot_product = np.dot(vector1, vector2)

In [27]:
print(dot_product)

198


# Matrix multiplication

In [40]:
data2 = np.array(np.random.randint(1, 100, size=9)).reshape(3,3)

In [41]:
data_part_3_3 = data[:3, :3]

In [42]:
data2

array([[ 7, 98, 59],
       [58, 62, 46],
       [61, 38, 11]])

In [43]:
dot_product_matrix = np.dot(data_part_3_3, data2)

In [44]:
print(dot_product_matrix)

[[ 8372  7768  4024]
 [ 6334 10706  6388]
 [ 4390  7424  4114]]


# Identity matrix

In [46]:
identity_matrix = np.identity(3) * 2

In [49]:
inverse_matrix = np.linalg.inv(identity_matrix)

In [50]:
print(inverse_matrix)

[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


# Eigenvalues and eigenvectors

In [51]:
eigenvalues, eigenvectors = np.linalg.eig(data_part)

In [52]:
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [136.30648146 -41.4960684   20.18958694]
Eigenvectors:
 [[-0.59367014 -0.86908838  0.15597481]
 [-0.66609434  0.35067479 -0.86705977]
 [-0.4515242   0.34887331  0.47315876]]


# Find missing values

In [69]:
data_replaced_nan = data.copy()

In [70]:
missing_indices = np.random.choice(data.size, 5, replace=False)

# Replace missing values

In [73]:
matrix_mean = np.nanmean(data_replaced_nan)

In [74]:
data_with_mean = np.where(np.isnan(data_replaced_nan), matrix_mean, data_replaced_nan)

In [75]:
print(data_with_mean)

[[14. 48. 90. 42. 11.]
 [57. 55. 45. 90. 28.]
 [44. 22. 46. 75. 45.]
 [76.  2. 74. 10. 42.]
 [26. 71. 18. 42. 31.]]
