In [22]:
import numpy as np

# Matrix Manipulation

In [11]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)

In [18]:
data

array([[95, 13,  5, 17, 89],
       [41, 50, 75,  6, 25],
       [35, 37,  4, 53, 12],
       [99, 97, 43, 66,  8],
       [63, 49, 54, 36, 71]])

In [33]:
data[[1,3]] = data[[3,1]]

In [34]:
print(data)

[[95 13  5 17 89]
 [41 50 75  6 25]
 [35 37  4 53 12]
 [99 97 43 66  8]
 [63 49 54 36 71]]


# Normalization

In [23]:
min_value = np.min(data)

In [24]:
max_value = np.max(data)

In [26]:
print((data - min_value) / (max_value - min_value))

[[0.95789474 0.09473684 0.01052632 0.13684211 0.89473684]
 [1.         0.97894737 0.41052632 0.65263158 0.04210526]
 [0.32631579 0.34736842 0.         0.51578947 0.08421053]
 [0.38947368 0.48421053 0.74736842 0.02105263 0.22105263]
 [0.62105263 0.47368421 0.52631579 0.33684211 0.70526316]]


# Z-score normalization

In [35]:
mean = np.mean(data, axis=0)

In [36]:
std = np.std(data, axis=0)

In [37]:
print((data - mean) / std)

[[ 1.06987908 -1.32275453 -1.12018797 -0.84039957  1.46194777]
 [-0.96439804  0.02923214  1.39305427 -1.33741007 -0.48731592]
 [-1.19042883 -0.4457902  -1.15609143  0.78618024 -0.88326011]
 [ 1.22056627  1.74662063  0.24414353  1.37355628 -1.00508909]
 [-0.13561847 -0.00730804  0.6390816   0.01807311  0.91371736]]


# Z-score normalization